### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by lag00n** [wooosh/dots#1]
Can you please add the terminal background pixmap? I really like it :D 

Thanks in advance

**Comment by wooosh** [comment]
Yes! I will upload it in a minute or two. I forgot to include in my copy dots script.

**Comment by wooosh** [comment]
Pushed!

https://github.com/wooosh/dots/blob/master/.config/urxvtpixmap.png

Eventually I will write an imagemagick script to create these automatically for a given font.

**Comment by lag00n** [comment]
Thanks! I really like that

Love ur rice!
